#!/bin/bash

sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.bolt
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.bolt.rain
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.drizzle
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.fog
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.hail
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.heavyrain
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.moon.bolt
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.rain
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.sleet
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.snow
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.sun.bolt
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.sun
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name cloud.sun.rain
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name hurricane
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name moon
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name moon.stars
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name smoke
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name snow
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name sun.dust
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name sun.haze
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name sun.max
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name sun.min
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name thermometer.snowflake
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name thermometer.sun
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name tornado
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name tropicalstorm
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name wind
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name wind.snow
sfsymbols --font-size 120 --font-weight medium --format pdf --symbol-name wrench